using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using CAT.AID.Models;

namespace CAT.AID.Web.Services.PDF
{
    public class BasePdfTemplate
    {
        public static string LogoLeft => "wwwroot/Images/20240912282747915.png";
        public static string LogoRight => "wwwroot/Images/202409121913074416.png";

        // Color Theme
        public static readonly string PrimaryColor = "#003366";
        public static readonly string AccentColor = "#0A74DA";
        public static readonly string LightBlue = "#E9F1FB";

        // ----------------------------------------------------------
        // HEADER WITH TWO LOGOS + TITLE
        // ----------------------------------------------------------
        public static void BuildHeader(RowDescriptor row, string title)
        {
            row.ConstantItem(80).Image(LogoLeft);

            row.RelativeItem().Column(col =>
            {
                col.Item()
                    .Text(title)
                    .FontSize(20)
                    .Bold()
                    .FontColor(PrimaryColor)
                    .AlignCenter();

                col.Item().Height(4);
                col.Item().BorderBottom(1).BorderColor(PrimaryColor);
            });

            row.ConstantItem(80).Image(LogoRight);
        }

        // ----------------------------------------------------------
        // FOOTER WITH PAGE NUMBERS
        // ----------------------------------------------------------
        public static void BuildFooter(RowDescriptor row)
        {
            row.RelativeItem().Text(text =>
            {
                text.Span("Generated by CAT-AID System").FontSize(9);
            });

            row.ConstantItem(100).AlignRight().Text(text =>
            {
                text.CurrentPageNumber().FontSize(10);
                text.Span(" / ");
                text.TotalPages().FontSize(10);
            });
        }

        // ----------------------------------------------------------
        // CANDIDATE INFORMATION BLOCK
        // ----------------------------------------------------------
        public static void BuildCandidateBlock(ColumnDescriptor col, Candidate c)
        {
            col.Item().Background(LightBlue).Padding(10).Column(inner =>
            {
                inner.Item().Text("Candidate Information")
                    .FontSize(14)
                    .Bold()
                    .FontColor(PrimaryColor);

                inner.Item().Text(txt =>
                {
                    txt.Span("Name: ").Bold();
                    txt.Span(c.FullName);
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("Gender: ").Bold();
                    txt.Span(c.Gender);
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("DOB: ").Bold();
                    txt.Span(c.DOB.ToString("dd-MMM-yyyy"));
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("Disability Type: ").Bold();
                    txt.Span(c.DisabilityType);
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("Education: ").Bold();
                    txt.Span(c.Education);
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("Address: ").Bold();
                    txt.Span(c.CommunicationAddress);
                });

                inner.Item().Text(txt =>
                {
                    txt.Span("Contact: ").Bold();
                    txt.Span(c.ContactNumber);
                });
            });
        }

        // ----------------------------------------------------------
        // ASSESSOR SIGNATURE BLOCK
        // ----------------------------------------------------------
        public static void BuildSignatureBlock(ColumnDescriptor col, string assessorName, string leadName)
        {
            col.Item().PaddingTop(15).Row(row =>
            {
                // Assessor
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("Assessor").Bold();
                    c.Item().Height(40);
                    c.Item().BorderBottom(1);
                    c.Item().Text(assessorName).FontSize(11);
                });

                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("Lead Assessor").Bold();
                    c.Item().Height(40);
                    c.Item().BorderBottom(1);
                    c.Item().Text(leadName).FontSize(11);
                });
            });
        }

        // ----------------------------------------------------------
        // REUSABLE TABLE STYLE
        // ----------------------------------------------------------
        public static void BuildStyledTable(TableDescriptor table, string[] headers)
        {
            table.ColumnsDefinition(col =>
            {
                foreach (var h in headers)
                    col.RelativeColumn();
            });

            // TABLE HEADER
            table.Header(h =>
            {
                foreach (var header in headers)
                {
                    h.Cell().Background(PrimaryColor)
                        .Padding(6)
                        .Text(header)
                        .FontColor("white")
                        .Bold();
                }
            });
        }
    }
}
